Feat/authentication
inlivedev/live-streaming-essential-kit pull request #12
Opened 2022-10-14 11:22 UTC by diahasumsi

**Description**
Before creating stream, authentication needed to validate user's credential.
Once the user credential validated, a token will be generated which is used to validate each process during the creation of the stream until the end of the stream.

**Implementation**
- Inside the component create stream make sure user is authenticated by hitting endpoint '/api/auth/login' with http method post
- After user authenticated, should generate token as a validator to the next process by hitting endpoint '/api/auth/generateToken' with http method post. The generated token should be placed in cookie.
- Before each process, token should be validated by hitting endpoint 'api/auth/validate' and store the token in headers with http method post

2022-10-17 01:37 UTC, ingrid011 commented
@diahasumsi 
1. This is just a note how to write the PR.
Kindly mention issue number on the PR description field. I think it will help us because if we push to prod, we will list all the PRs and its own issue per PR too.
2. Also, could you help to add how to use it (just an example) in the implementation field or just in this comment?
So far (from my experience with backend), it will help FE to know the picture on how to implement/use it on FE too if you mention it on this PR.
(cmiiw or anything else : mas @faiq-naufal )

Thank you before!

2022-10-17 02:35 UTC, faiq-naufal requested changes
Please check the comment

2022-10-17 02:35 UTC, faiq-naufal commented on src/pages/api/auth/[name].js
> +  if (name == 'login') {
the name `login` is too general. what if in the future we add more login mechanisms such as oauth? I think we should change the `login` into `login-with-credentials`. what do you think? Or do you have alternative name?

2022-10-17 02:35 UTC, faiq-naufal commented on src/pages/api/auth/[name].js
> +  } else if (name == 'generateToken') {
1. Just reminder to use the strict equality
2. `/api/auth/generateToken` camelCase is not suitable for endpoint URL. When we define a URL, better to use kebab-case convention. So, this should be `/api/auth/generate-token` something like this.

2022-10-17 02:35 UTC, faiq-naufal commented on src/pages/api/auth/[name].js
> +  const { JWT_SECRET, JWT_EXPIRES_IN } = process.env;
`JWT_SECRET` and `JWT_EXPIRES_IN` should be put inside the `.env.example` file **without the value**. Ex: `JWT_SECRET=` Also I still don't know how to set those two. Can you provide a description of how to set those ENV variables?

2022-10-17 02:35 UTC, faiq-naufal commented on src/pages/api/auth/[name].js
> +      username === 'username' && password === 'password';
Why do we need to double-check the credentials for `login` and `generate-token`? The generate token endpoint is simply to generate a token and this endpoint **should not** be called from the client side (only call this on server side). This endpoint or function should be part of the login mechanism above and **should not** be called separately from the client.

2022-10-17 02:35 UTC, faiq-naufal commented on src/pages/api/auth/[name].js
> +      if (!request.headers.authorization)
When we send a cookie to the validation endpoint, the mechanism to get and send the cookie will be run on the server side only because we will use HTTP only cookie which cannot be accessed through the client side javascript.

2022-10-17 11:15 UTC, faiq-naufal requested changes
I have additional comments

2022-10-17 11:15 UTC, faiq-naufal commented on src/pages/api/auth/[name].js
> +        sameSite: 'strict'
this cookie is still not `httponly` cookie. Add `httpOnly: true` to make it httponly cookie

2022-10-18 02:38 UTC, diahasumsi commented on package.json
> +    "fastify": "4.7.0",
Hi Mas, already reverted it to v 4.8.1  this commit https://github.com/inlivedev/live-streaming-essential-kit/pull/12/commits/0a92ce5a4a511351f4f1095df9bfeee15b098dfb

2022-10-18 02:39 UTC, diahasumsi commented on package.json
> +    "fastify-cookie": "^5.7.0",
changed the package and did some revision by this commit https://github.com/inlivedev/live-streaming-essential-kit/pull/12/commits/26102ff709c0ab2cfce9ba22843d90c4b92ff498

2022-10-18 02:42 UTC, diahasumsi commented on package.json
> +    "jsonwebtoken": "^8.5.1",
i decided to use @fastify/jwt as advice, because it makes sense to use packages that are still maintained, also more efficient in its use, so I did some revision by this commit https://github.com/inlivedev/live-streaming-essential-kit/pull/12/commits/7015db55acd6607dc1eee5f46f5c0e8870125ae7

2022-10-18 02:44 UTC, diahasumsi commented on src/pages/api/auth/[name].js
> +        sameSite: 'strict'
i missed it and already revised it by this commit https://github.com/inlivedev/live-streaming-essential-kit/pull/12/commits/675a6de1e9f3294e38a1dd011fea3e3e3a689343#diff-f4a49e337745444f7186964ef6b727d40508960f8f14da8cc2fcbb3290ff4068

2022-10-18 10:13 UTC, ingrid011 reviewed
I've got a question as per below. Kindly advice.

2022-10-18 10:13 UTC, ingrid011 commented on .eslintrc.cjs
> +    'plugin:promise/recommended'
@diahasumsi , just would like to ask, is it okay to omit (take out) the `plugin:unicorn/recommended`? Is there any reason?
Because I think this plugin help us to define best practice to code and also on our `dev` branch already use it.

2022-10-18 10:18 UTC, diahasumsi commented on .eslintrc.cjs
> +    'plugin:promise/recommended'
Hi Kak thank you for your concern, i have resolved it here https://github.com/inlivedev/live-streaming-essential-kit/pull/12/commits/b825b13d394ff0c59735119a042bcab345baa7fa

2022-10-18 10:54 UTC, faiq-naufal requested changes

2022-10-18 10:54 UTC, faiq-naufal commented on src/pages/api/auth/[name].js
> +  }
there is no http method checking which method the client should be allowed when interacting with both login and validation. In this case, the client can freely hit the auth endpoint by using `delete` or `put` methods and still working fine isn't it?

2022-10-18 10:54 UTC, faiq-naufal commented on src/pages/api/auth/[name].js
> +  }
the login and validation should only allow for `post` request and should disallow any other method requests

2022-10-18 10:55 UTC, faiq-naufal commented
Don't forget to update the description of this PR

2022-10-19 02:06 UTC, ingrid011 approved these changes
LGTM, but better to merge until mas @faiq-naufal review.

2022-10-19 02:24 UTC, faiq-naufal approved these changes
LGTM. I still think we can make the logic better, but we can improve that in the future implementation.

2022-10-19 02:26 UTC, merged