create handler for create until end stream
inlivedev/live-streaming-essential-kit pull request #19
Opened 2022-10-19 01:06 UTC by diahasumsi

2022-10-19 05:46 UTC, faiq-naufal requested changes

2022-10-19 05:46 UTC, faiq-naufal commented on src/pages/api/stream/[name].js
> +};
Isn't this function basically the same as the validation authentication logic? Why didn't you just use that logic?

2022-10-19 05:46 UTC, faiq-naufal commented on src/pages/api/stream/[name].js
> +        stream_id: request.body.stream_id
`request.body.stream_id` should be =>  `request.body.streamId`. Use camelCase for request body and keep the property key `stream_id` for now. The SDK accept `stream_id` key property which was our previous mistake and will be fixed and changed into camelCase later

2022-10-20 10:45 UTC, ingrid011 requested changes
@diahasumsi kindly recheck your code as per below.
Also, I've did trial to create stream by using fetch /api/stream/create . However, somewhat the return that I got on my side is {success = true} instead of create stream data.
When I used back your old code (reference as per glitch) on /api/stream/[name].js, it will react as normal to return create stream data.
Kindly help to check it too.

Thanks.

2022-10-20 10:56 UTC, ingrid011 requested changes

2022-10-20 10:56 UTC, ingrid011 commented on src/pages/api/auth/validation.js
> +};
@diahasumsi I think I know the problem why my create stream return data is weird. You should recheck this function because if I used your commented validation function before (which you decided not using it) in here, it can run well.

2022-10-20 11:08 UTC, diahasumsi commented on src/pages/api/auth/validation.js
> +    return false;
Hi Kak, sorry i tried test the code, but forgot to revert to how its supposed to be, the code is fixed by this [commit](https://github.com/inlivedev/live-streaming-essential-kit/pull/19/commits/f29f62f83c3303182ee539786598e84f033f5ec8) please kindly recheck

2022-10-21 01:55 UTC, ingrid011 commented on src/pages/api/auth/validation.js
> +};
resolved at commit [f29f62f](https://github.com/inlivedev/live-streaming-essential-kit/pull/19/commits/f29f62f83c3303182ee539786598e84f033f5ec8)

2022-10-21 02:01 UTC, ingrid011 approved these changes
Is LGTM for me now. But please wait mas @faiq-naufal for re-review before merging it. 
Also, kindly comment / resolved previous changes requests if you've done it, and ask for re-review, so we can track it well when we need to re-review this PR. Thank you.

2022-10-21 02:33 UTC, faiq-naufal commented on src/pages/api/stream/[name].js
> +  if (request.method !== 'POST') {
I forget previously to tell you to make this `POST` word flexible. Don't make the client should write the exact `POST` word. What if they want to write `post` instead? Ensure the request.method is uppercase by converting the value into uppercase, and then compare the value

2022-10-21 05:41 UTC, diahasumsi commented on src/pages/api/stream/[name].js
> +  if (request.method !== 'POST') {
I forgot to handle this too. Thank you for this. I fixed it by this commit, please kindly check [here](https://github.com/inlivedev/live-streaming-essential-kit/pull/19/commits/f2c8626efcc42270ad6d2bba9b2760c62444e8bd)

2022-10-21 06:48 UTC, faiq-naufal requested changes
Sorry, there are a lot of comments related with negative case / error handling

2022-10-21 06:48 UTC, faiq-naufal commented on src/pages/api/stream/[name].js
> +        throw new Error(error);
`throw new Error(error);` will expect a string. Just `throw error` without `new Error()` will throw the actual error data response from API request which can be an object to the client/front-end. The front-end will handle that error instead. @ingrid011 @diahasumsi

2022-10-21 06:48 UTC, faiq-naufal commented on src/pages/api/stream/[name].js
> +    // No default
> Switch cases should almost always have a default case

https://stackoverflow.com/a/5241196

1. Better to include the default with empty logic
2. Just use the if else instead

2022-10-21 06:48 UTC, faiq-naufal commented on src/pages/api/stream/[name].js
> +        throw new Error(error);
See comment above, just throw this error without `new Error()`

2022-10-21 06:48 UTC, faiq-naufal commented on src/pages/api/stream/[name].js
> +          });
This `else` is not needed, when the SDK throws an error, it will directly pass to the `catch` logic

2022-10-21 06:48 UTC, faiq-naufal commented on src/pages/api/stream/[name].js
> +        throw new Error(error);
See comment above, just throw this error without `new Error()`

2022-10-21 06:48 UTC, faiq-naufal commented on src/pages/api/stream/[name].js
> +          });
This `else` is not needed, when the SDK throws an error, it will directly pass to the `catch` logic

2022-10-21 06:48 UTC, faiq-naufal commented on src/pages/api/stream/[name].js
> +          });
This `else` is not needed, when the SDK throws an error, it will directly pass to the `catch` logic

2022-10-21 06:48 UTC, faiq-naufal commented on src/pages/api/stream/[name].js
> +        throw new Error(error);
See comment above, just throw this error without `new Error()`

2022-10-21 06:48 UTC, faiq-naufal commented on src/pages/api/stream/[name].js
> +          });
just pass the response like this
```js
reply.code(dataStream.status.code).send(dataStream);
```

2022-10-21 06:48 UTC, faiq-naufal commented on src/pages/api/stream/[name].js
> +          });
just pass the response like this
```js
reply.code(dataStream.status.code).send(dataStream);
```

2022-10-21 06:48 UTC, faiq-naufal commented on src/pages/api/stream/[name].js
> +          });
just pass the response like this
```js
reply.code(dataStream.status.code).send(dataStream);
```

2022-10-21 07:05 UTC, ingrid011 commented on src/pages/api/stream/[name].js
> +        throw new Error(error);
@faiq-naufal @diahasumsi I think with `throw error` can be applicable since the error data response from API request will be sent as an object in the future. For now, if the code change like that, seems still fine (same workable).

2022-10-21 07:09 UTC, ingrid011 commented on src/pages/api/stream/[name].js
> +          });
@faiq-naufal @diahasumsi actually same my opinion as [below](https://github.com/inlivedev/live-streaming-essential-kit/pull/19#discussion_r1001439848) comment though. 
Also, on our previous SDK planning, the structure of error response will be similar as in this code, so I think it's fine. But I need to keep it as a note first, once we've implemented the object structure on the SDK, then I need to adjust on getting the error message code on the create stream component (just sharing my note thought).

2022-10-21 07:45 UTC, diahasumsi commented on src/pages/api/stream/[name].js
> +          });
ok lets do that until SDK can provide its own response

2022-10-23 04:06 UTC, faiq-naufal commented on src/pages/api/stream/[name].js
> +    // No default
@diahasumsi I changed the conditional logic to use switch case again to follow the eslint rule and recommendation.

2022-10-23 04:09 UTC, faiq-naufal commented on src/pages/api/stream/[name].js
> +        throw new Error(error);
I just realized we don't need to `catch` the error if we just want to throw the error to the client. Fastify already handles that. Fastify will log the error on the server side and throw the error to the client side.

2022-10-23 04:13 UTC, faiq-naufal approved these changes
I updated some logic. This is already LGTM. Feel free to ask if there are additional questions.

2022-10-24 01:36 UTC, ingrid011 approved these changes
LGTM.

2022-10-24 01:36 UTC, merged