Feat : Create Stream
inlivedev/live-streaming-essential-kit pull request #5
Opened 2022-10-10 10:30 UTC by ingrid011

**Description**
TBA

2022-10-19 09:23 UTC, ingrid011 commented on .eslintrc.cjs
> +    'unicorn/prefer-node-protocol': 'off'
`unicorn prefer-node-protocol` needs to be disable first because need to use newest Node.js version if we would like to code as `node:path`

2022-10-19 09:29 UTC, ingrid011 commented on src/features/streamer/app-create-stream.js
> +    }
if title stream already input (`configObject.name`), then will execute the fetch api proxy create endpoint. If not checking it, it read the `""` can be created a stream (I don't know, but at least I've checked).

I add `.catch` to catch the error, because the error return data from the create stream handler needs to be catched. So, I think it useful for the user to know what kind of problem though, that's why I use `alert` to show the problem message (in case if demo there's an error).

If the return data is successful, after then will direct to the streaming studio page.

2022-10-19 09:34 UTC, ingrid011 commented on src/pages/index.js
> +const password = prompt('input your password');
will triggering pop up windows to input username & password

2022-10-19 09:42 UTC, ingrid011 commented on src/pages/index.js
> +userAuthentication();
This one flow :
1. After the user input the username & password, then will trigger `userAuthentication` function.
2. This `userAuthentication` will send the username & password to login-with-credentials endpoint.
3. The return from number 2, if success, then will process to checking the validation using `checkAuthValidation` function.
If not success, it will return rendering a sentence message to input valid username & password on the page.
4. This `checkAuthValidation` will just send blank `JSON.stringify({})` body because it's required if `'Content-Type': 'application/json'` to auth validation endpoint.
5. If return number 4 success, then it will display render the `app-create-stream` form component. 
If not, will return rendering a sentence error message.

2022-10-19 09:43 UTC, ingrid011 commented on src/scripts/server.js
> +      throw new Error(`Error starting server: ${error}`);
This is related to fix `server.js` unicorn error.
It been asked to use throw new Error as per [documentation](https://eslint.org/docs/latest/rules/no-process-exit).

2022-10-20 11:05 UTC, ingrid011 commented on src/pages/index.js
> +userAuthentication();
trigger login function to `/api/auth/login-with-credentials` endpoint. If the auth process return as success, then will display `create-stream-component`. If not success, then will return error message.

2022-10-21 02:26 UTC, faiq-naufal requested changes
Please check the comments

2022-10-21 02:26 UTC, faiq-naufal commented on src/pages/index.js
> +  });
Can you change this to use `fetchHttp` module instead?

2022-10-21 02:26 UTC, faiq-naufal commented on src/pages/index.js
> +};
Why didn't you just put this logic inside a component and handle the rendering logic using the lit way?

2022-10-21 02:26 UTC, faiq-naufal commented on src/pages/index.js
> +const password = prompt('input your password');
This logic can also be included inside the component. Just create a high level page component or make the `app-create-stream` component to be a high level component to handle the auth logic

2022-10-21 02:26 UTC, faiq-naufal commented on src/features/streamer/app-create-stream.js
> +        return (window.location.href = `/streaming/studio/${createStreamResponse.data.id}`);
I think you don't need to `return` the `window.location.href`. Just `window.location.href` is enough

2022-10-21 02:26 UTC, faiq-naufal commented on src/features/streamer/app-create-stream.js
> +          <button type="submit" class="submit-button" @click=${this.submit}>
Better to use form onsubmit event on `<form>` element than click event when submitting the form. For example `<form @submit=${this.handleSubmit}>`. Keep the button type with `submit` type. You can capture the  form element `create-stream-form` by using `event.target`

2022-10-21 02:26 UTC, faiq-naufal commented on src/features/streamer/app-create-stream.js
> +      showErrorText: { type: Boolean }
If `showErrorText` only for internal state of this component. Consider to make it an internal state by using `{ state: true }` instead. See this [reference](https://lit.dev/docs/components/properties/#:~:text=Lit%20also%20supports%20internal%20reactive%20state.%20Internal%20reactive%20state%20refers%20to%20reactive%20properties%20that%20aren%27t%20part%20of%20the%20component%27s%20API.%20These%20properties%20don%27t%20have%20a%20corresponding%20attribute%2C%20and%20are%20typically%20marked%20protected%20or%20private%20in%20TypeScript.)

2022-10-21 02:26 UTC, faiq-naufal commented on src/pages/index.js
> +userAuthentication();
I think it's better to put this logic inside a component than injecting directly into html.

2022-10-21 06:22 UTC, ingrid011 commented on src/features/streamer/app-create-stream.js
> +      showErrorText: { type: Boolean }
@faiq-naufal done at commit [33ab008](https://github.com/inlivedev/live-streaming-essential-kit/pull/5/commits/33ab008ae87865165775ecf3c06480a6d0b43c01). Thanks for the input mas.

2022-10-21 06:22 UTC, ingrid011 commented on src/features/streamer/app-create-stream.js
> +          <button type="submit" class="submit-button" @click=${this.submit}>
@faiq-naufal done at commit [33ab008](https://github.com/inlivedev/live-streaming-essential-kit/pull/5/commits/33ab008ae87865165775ecf3c06480a6d0b43c01)

2022-10-21 06:22 UTC, ingrid011 commented on src/features/streamer/app-create-stream.js
> +        return (window.location.href = `/streaming/studio/${createStreamResponse.data.id}`);
@faiq-naufal done at commit [33ab008](https://github.com/inlivedev/live-streaming-essential-kit/pull/5/commits/33ab008ae87865165775ecf3c06480a6d0b43c01)

2022-10-21 06:23 UTC, ingrid011 commented on src/pages/index.js
> +  });
@faiq-naufal yups already can mas, just need to adjust little bit but it's fine. Done at commit [35de929](https://github.com/inlivedev/live-streaming-essential-kit/pull/5/commits/35de92999f80bf591ed29199d0d1fbc3438cd5ab). Thanks.

2022-10-21 06:23 UTC, ingrid011 commented on src/pages/index.js
> +userAuthentication();
@faiq-naufal Done at commit [35de929](https://github.com/inlivedev/live-streaming-essential-kit/pull/5/commits/35de92999f80bf591ed29199d0d1fbc3438cd5ab)

2022-10-21 06:24 UTC, ingrid011 commented on src/pages/index.js
> +const password = prompt('input your password');
@faiq-naufal Done at commit [35de929](https://github.com/inlivedev/live-streaming-essential-kit/pull/5/commits/35de92999f80bf591ed29199d0d1fbc3438cd5ab).
Since most of the comments are regarding this one, I've resolved some ya mas..

Kindly help to recheck if codes like this is okay. Thank you.

2022-10-21 07:39 UTC, diahasumsi commented
LGTM

2022-10-21 07:41 UTC, diahasumsi approved these changes
LGTM

2022-10-21 07:43 UTC, merged