Feat : Viewer Landing Page
inlivedev/live-streaming-essential-kit pull request #9
Opened 2022-10-13 08:57 UTC by ingrid011

**Description**
This is related to issue #6 
We need to add the viewer landing page based on figma :  https://www.figma.com/file/75d6L7Zf2r8MwzEcxoOmUQ/InLive-Kit?node-id=5803%3A7257
There're some improvements though. Kindly read below notes what have been done

**Implementation**
- Creating the landing page with name `/preview-live-stream/{streamId}`. It's on the `pages` folder. It's already dynamic based on the stream ID.
- On the `getServerSideProps`, I fetch the `getStream(streamId)` SDK module to get the stream data.
- Above file will render `app-viewer-landing` component, which I divided into :
  - `viewer-top-bar` component :
    - will show the stream date based on figma design : I convert `start_time` with a `Intl.DateTimeFormat` function (because on the design can show WIB -- this is the easiest way)
     - will show "LIVE" status. I improved it by checking `start_time` & `end_time` (because I think since this page will dynamically render by its stream ID). If the conditions meet, then can also show as "UPCOMING" or "ENDED". Later, this one can be replace with lozenges component as same as streamer component.
<img width="283" alt="Screen Shot 2022-10-13 at 14 34 04" src="https://user-images.githubusercontent.com/102952824/195551024-f4f3b497-9e84-4c26-8085-8271a6cf0e20.png">
<img width="257" alt="Screen Shot 2022-10-13 at 14 32 19" src="https://user-images.githubusercontent.com/102952824/195551056-4413560a-1c22-4ea9-8dd5-ece95a40758a.png">
<img width="292" alt="Screen Shot 2022-10-13 at 14 30 33" src="https://user-images.githubusercontent.com/102952824/195551084-1c6a82ec-624d-42fb-b9d5-fea626e613bd.png">

   
   - `viewer-stream-info` component :  
     -  Just showing the stream title & stream description
   -  `viewer-join-live` component : 
      - Is a form to input the username. I set it dynamic show too based on live/upcoming/ended status. If live, this form will show, but if upcoming/ended the form won't show.
      - Already include input username checking min 3 characters & alphanumeric only
      - The input username will be stored on localStorage as name `viewer-username`
      - Then, it will go to the next page, for now I just go to `/watch-live-stream/{streamId}` page (still not yet have this page).

2022-10-13 09:05 UTC, ingrid011 commented on src/features/viewer/landing/viewer-join-live.js
> +      localStorage.setItem('viewer-username', username);
saving to local storage as name `viewer-username`

2022-10-13 09:06 UTC, ingrid011 commented on src/features/viewer/landing/viewer-join-live.js
> +      return window.location.replace('/watch-live-stream/' + this.streamId);
then go to the next page. In here I named it as `/watch-live-stream` page

2022-10-13 09:07 UTC, ingrid011 commented on src/features/viewer/landing/viewer-top-bar.js
> +          : null}
rendering different status. But I think this one can be replace with lozenges same with the streamer component later on.

2022-10-13 09:13 UTC, ingrid011 commented on src/ssr/template.js
> +            padding: 0;
Really need this because it's so annoying that the margin & padding are there. So I think it's better to reset it from template

2022-10-13 09:14 UTC, ingrid011 commented on src/pages/preview-live-stream/[streamId].js
> +        (streamData.data.end_time === null || streamData.data.end_time === '')
Checking conditions for rendering status on top bar component according to the data. I think we need this first because the page is dynamic, so there will be stream which is already ended, or still not started yet too.

2022-10-13 09:15 UTC, ingrid011 commented on src/pages/preview-live-stream/[streamId].js
> +    }).format(datetime);
with 'id' because on the figma mock is using WIB

2022-10-14 02:46 UTC, faiq-naufal requested changes

2022-10-14 02:46 UTC, faiq-naufal commented on src/features/viewer/landing/app-viewer-landing.js
> +      isLive: { type: String }
If you are only checking for boolean value, just using the actual boolean not a string. Please change `isScheduled`, `isEnded`, and `isLive` to a boolean type

2022-10-14 02:46 UTC, faiq-naufal commented on src/features/viewer/landing/viewer-top-bar.js
> +      isLive: { type: String }
Please change `isScheduled`, `isEnded`, and `isLive` to boolean types too

2022-10-14 02:46 UTC, faiq-naufal commented on src/pages/preview-live-stream/[streamId].js
> +        (streamData.data.start_time === '' && streamData.data.end_time === ''),
To check whether the data null or empty string you can using negation (logical not). `!streamData.data.start_time` or `!streamData.data.end_time ` something like these will work

2022-10-14 02:46 UTC, faiq-naufal commented on src/features/viewer/landing/viewer-join-live.js
> +      @media (min-width: 640px) {
We will consider the tablet view as a mobile view so the desktop view should be from `1024px`

2022-10-14 07:37 UTC, ingrid011 commented on src/features/viewer/landing/app-viewer-landing.js
> +      isLive: { type: String }
@faiq-naufal regarding this one, I've done several experiment :
1. on the `app-viewer-landing` & `viewer-top-bar` passing boolean value with `.` prefix & static properties type to `Boolean` :
  - I've checked on the `app-viewer-landing`, yes it will received `typeof` boolean value. However the passing value not correct. Eg. if I set `isScheduled` value is `true`, then all of the received values on the `app-viewer-landing` is `true`. But if I re-set the properties type to `String` again, the values are correct (so I conclude values are read as a String (?) in child components -- since on the page is typeof boolean though).
   - So, when I pass it again to `viewer-top-bar` will be all `true` as well if `app-viewer-landing` values are `true`.
<img width="352" alt="Screen Shot 2022-10-14 at 13 15 50" src="https://user-images.githubusercontent.com/102952824/195787087-2334d6ff-e86c-43c2-860c-1a1b1678cd63.png">

   
   
2. If from the top (from [streamId].js page), I pass it using `.` prefix & static properties type to `Boolean` and prefix on `app-viewer-landing` & `viewer-top-bar` : 
   - Will read as `undefined` values on the `app-viewer-landing` & `viewer-top-bar` components.
<img width="455" alt="Screen Shot 2022-10-14 at 13 13 53" src="https://user-images.githubusercontent.com/102952824/195787121-e8e61a58-5baf-47a5-96b6-f9370e7b0d32.png">

Done several experiment, but for passing with `.` prefix for boolean value from the [streamId].js page to lit component will read as `undefined` on the component.
   
3. Trial using code like this : `.prop3="${false}"` according to [this](https://github.com/lit/lit-element/issues/819).
   - Result same as number 1 or can be `undefined` as number 2
 
Kindly note, I trial as above without constructor value first to see if it works or not.
If using constructor, of course if `undefined` will write as the constructor value.

Kindly advice mas since I couldn't find reference to solve this ? Or for now just use same as this code with String type ?

2022-10-14 07:38 UTC, ingrid011 commented on src/pages/preview-live-stream/[streamId].js
> +        (streamData.data.start_time === '' && streamData.data.end_time === ''),
@faiq-naufal done at commit [b5d2a80](https://github.com/inlivedev/live-streaming-essential-kit/pull/9/commits/b5d2a80cfd1c14cc80e001eb4bea776f21f0d38f)

2022-10-14 07:38 UTC, ingrid011 commented on src/features/viewer/landing/viewer-join-live.js
> +      @media (min-width: 640px) {
@faiq-naufal done at commit [2913b45](https://github.com/inlivedev/live-streaming-essential-kit/pull/9/commits/2913b45caf7b1098e207c4dccc007cd5d805bb68)

2022-10-14 07:38 UTC, ingrid011 commented on src/features/viewer/landing/viewer-top-bar.js
> +      isLive: { type: String }
same question with this [above comment ](https://github.com/inlivedev/live-streaming-essential-kit/pull/9#discussion_r995443337)

2022-10-14 08:38 UTC, faiq-naufal commented on src/features/viewer/landing/app-viewer-landing.js
> +      isLive: { type: String }
> passing with . prefix for boolean value from the [streamId].js page to lit component will read as undefined on the component

About the `.` prefix I think we cannot use this inside the current pages component because the component will be rendered on server side and the `.` prefix is on the client-side scope. So, yeah it will make the value `undefined`. We cannot use `.` prefix on the page level component for now.

2022-10-14 08:41 UTC, faiq-naufal commented on src/features/viewer/landing/app-viewer-landing.js
> +      isLive: { type: String }
You don't need `.` prefix to pass the boolean value to the component. Using `{ type: Boolean }` will convert the property into boolean type

2022-10-14 08:45 UTC, faiq-naufal commented on src/features/viewer/landing/app-viewer-landing.js
> +      isLive: { type: String }
<img width="513" alt="Screen Shot 2022-10-14 at 15 44 30" src="https://user-images.githubusercontent.com/43695578/195803734-d3c60e34-c5db-4947-91b8-de39077977b4.png">

I can pass the value just fine through the component using `{ type: Boolean }` for the property

2022-10-14 09:01 UTC, ingrid011 commented on src/features/viewer/landing/app-viewer-landing.js
> +      isLive: { type: String }
@faiq-naufal 
have you tried to check all `isEnded`, `isScheduled`, `isLive` value?

because what I did (eg. supposedly just `isSchedule` is `true`):
1. yes, on the page [streamid] not use `.` prefix
2. on `app-viewer-landing` & `viewer-top-bar` components just using `{ type: Boolean }`

however, when I console log all the values the output will same to `true` value :
<img width="1440" alt="Screen Shot 2022-10-14 at 15 55 34" src="https://user-images.githubusercontent.com/102952824/195806964-bbcd438b-c674-4bbe-8eae-673445fa7c2a.png">

is there something that I missed though? ^^"

2022-10-14 09:40 UTC, ingrid011 commented on src/features/viewer/landing/app-viewer-landing.js
> +      isLive: { type: String }
@faiq-naufal based on our huddle discussion, since the `boolean` values read as HTML, so I think for now I just refactor the code to be :
1. on page, add conditional that will check and save a value of `streamScheduled` or `streamEnded` or `streamLive` and save it to a variable called `streamStatus`
2. `streamStatus` will be pass as props into lit components as a `string`
3. Adjusting each components condition using `streamStatus` string value instead.

I done it at commit [2e09f31](https://github.com/inlivedev/live-streaming-essential-kit/pull/9/commits/2e09f316b4dbfb10902e060b8d2e20faf734c065)

Apologize for the confusion & inconvenience mas..

2022-10-14 09:43 UTC, ingrid011 commented on src/features/viewer/landing/viewer-top-bar.js
> +      isLive: { type: String }
same as [this comment](https://github.com/inlivedev/live-streaming-essential-kit/pull/9#discussion_r995564063)

2022-10-14 10:08 UTC, faiq-naufal approved these changes
LGTM

2022-10-14 10:50 UTC, merged